global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'rest_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rest-service:5012']
        labels:
          application: 'Demo Service Application'
